# Numpy

In [2]:
import numpy as np

## Lets do some basic stuff

In [5]:
a=np.array(5)
a

array(5)

## we convert 1 to 15 in 3*5 regtangle

In [12]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## calculate number of demention

In [17]:
a.shape

(15,)

In [19]:
a=a.reshape(3,5)
a.shape

(3, 5)

In [21]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3, 5)
2
15
int32


## For 3 dimention 

In [24]:
b=np.array(20)
b

array(20)

In [26]:
b=np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### 3 dimention

In [29]:
b=b.reshape(2,5,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [31]:
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(2, 5, 2)
3
20
int32


# Some operations

In [34]:
k = np.array([20, 30, 40, 50])
k

array([20, 30, 40, 50])

In [36]:
d=np.arange(4)

In [38]:
d

array([0, 1, 2, 3])

In [40]:
k

array([20, 30, 40, 50])

In [42]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [44]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [46]:
k-d

array([20, 29, 38, 47])

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
k+d

array([20, 31, 42, 53])

In [54]:
k

array([20, 30, 40, 50])

In [56]:
d

array([0, 1, 2, 3])

In [58]:
c = k * d
c

array([  0,  30,  80, 150])

In [60]:
k = np.array([20, 30, 40, 50])
d=np.arange(4)
g=k+d
h=k-d
c = k * d
print(k)
print(d)
print(g)
print(h)
print(c)

[20 30 40 50]
[0 1 2 3]
[20 31 42 53]
[20 29 38 47]
[  0  30  80 150]


In [62]:
c>50

array([False, False,  True,  True])

In [64]:
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])

##### Lets do some other stuffs/ here are some special matrixs

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [75]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x.shape = (2, 5)  # now x is 2-dimensional
x[1, 3]
x[1, -1]

9

In [77]:
x[0][2]

2

In [79]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [81]:
x[-2:10]
x[-3:3:-1]

array([7, 6, 5, 4])

In [83]:
x[5:]

array([5, 6, 7, 8, 9])

In [85]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x.shape
x[1:2]

array([[[4],
        [5],
        [6]]])

In [87]:
x = np.arange(10, 1, -1)
x
x[np.array([3, 3, 1, 8])]
x[np.array([3, 3, -3, 8])]

array([7, 7, 4, 2])